#!/bin/sh

# ltrx-radio-down:
#   Turns off overall power and 32k clock to the bcm4339 device.
#
# RADIO_POWER_EN    (GPIO PC7, Power to radio = active LOW)
# BT_PWR_DN         (GPIO PC10, Bluetooth On = active HIGH)
# WL_PWR_DN         (GPIO PC9, Wlan On = active HIGH)
# WL_32KHZ          (PWM2 on PB13 peripheral B)
#

RADIO_DEVICES_FILE=/tmp/radio.devices
RADIO_UP_FILE=/tmp/radio.up

if [ ! -e $RADIO_DEVICES_FILE ]; then
#	echo "Exporting radio devices"
	ltrx-radio-export-devices
	if [ "$?" -ne "0" ] ; then
		echo "Failed to export radio devices" >&2
		exit 1
	fi
fi

if [ ! -e $RADIO_UP_FILE ]; then
#	echo "Radio is already down"
	exit 0
fi

# Turn everything off...
# drive radio's BT_REG_ON low
echo 0 > /sys/class/gpio/pioC10/value
# drive radio's WL_REG_ON low
echo 0 > /sys/class/gpio/pioC9/value
# disable PMIC output 6 (radio's VDDIO)
/usr/bin/i2cset -y 0 0x5b 0x61 0x41 b
# disable VBAT to radio
echo 1 > /sys/class/gpio/pioC7/value
# disable pwm2 output (32768 Hz clock)
echo 0 > /sys/class/pwm/pwmchip0/pwm2/enable

# At this point, everything is powered down
rm -f $RADIO_UP_FILE

exit 0
