#!/bin/sh
#
#/etc/ppp/ppp-off
#
######################################################################
#
# Determine the device to be terminated.

if [ -z "$1" ]; then
    DEVICE=ppp0
else
    DEVICE=$1
fi
######################################################################
#
# If the ppp0 pid file is present then the program is running. Stop it.

if [ -r /var/run/$DEVICE.pid ]; then
    kill -INT `cat /var/run/$DEVICE.pid`

    #####################################################################
    # If the kill did not work then there is no process running for this
    # this pid. It may also mean that the lock file will be left. You may
    # wish to delete the lock file at the same time.

    if [ ! \"$?\" = \"0\" ]; then
        rm -f /var/run/$DEVICE.pid
        echo \"ERROR: Removed stale pid file\"
        exit 1
    fi

    ######################################################################
    # Success. Let pppd clean up its own junk.

    logger \"PPP link to $DEVICE terminated.\"
    exit 0
fi

######################################################################
# The ppp process is not running for ppp0

logger \"ERROR: PPP link is not active on $DEVICE\"
exit 1

