#!/bin/sh
DAEMON=/usr/bin/dnsmasq
NAME=dnsmasq
DESC="DNS forwarder and DHCP server"
ARGS="-7 /etc/dnsmasq.d"

test -f $DAEMON || exit 0

set -e

logger "init.d $DESC: $NAME can only be started by the network service"

exit 0
